// DO NOT EDIT -- generated code

// Package agent - the agent communicates with pinpoint cloud to send integration data
package agent

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/bxcodec/faker"
	"github.com/pinpt/go-common/v10/datamodel"
	"github.com/pinpt/go-common/v10/hash"
	pjson "github.com/pinpt/go-common/v10/json"
	pstrings "github.com/pinpt/go-common/v10/strings"
)

const (

	// ValidateRequestTable is the default table name
	ValidateRequestTable datamodel.ModelNameType = "agent_validaterequest"

	// ValidateRequestModelName is the model name
	ValidateRequestModelName datamodel.ModelNameType = "agent.ValidateRequest"
)

const (
	// ValidateRequestModelConfigColumn is the column json value config
	ValidateRequestModelConfigColumn = "config"
	// ValidateRequestModelCustomerIDColumn is the column json value customer_id
	ValidateRequestModelCustomerIDColumn = "customer_id"
	// ValidateRequestModelEnrollmentIDColumn is the column json value enrollment_id
	ValidateRequestModelEnrollmentIDColumn = "enrollment_id"
	// ValidateRequestModelIDColumn is the column json value id
	ValidateRequestModelIDColumn = "id"
	// ValidateRequestModelIntegrationInstanceIDColumn is the column json value integration_instance_id
	ValidateRequestModelIntegrationInstanceIDColumn = "integration_instance_id"
	// ValidateRequestModelRefIDColumn is the column json value ref_id
	ValidateRequestModelRefIDColumn = "ref_id"
	// ValidateRequestModelRefTypeColumn is the column json value ref_type
	ValidateRequestModelRefTypeColumn = "ref_type"
	// ValidateRequestModelSessionIDColumn is the column json value session_id
	ValidateRequestModelSessionIDColumn = "session_id"
)

// ValidateRequest A validation request sent to the agent to do validation
type ValidateRequest struct {
	// Config The configuration from the UI to be validated in JSON format as a string
	Config string `json:"config" codec:"config" bson:"config" yaml:"config" faker:"-"`
	// CustomerID the customer id for the model instance
	CustomerID string `json:"customer_id" codec:"customer_id" bson:"customer_id" yaml:"customer_id" faker:"-"`
	// EnrollmentID The id of the on premise agent enrollment to route this to. Leave null for cloud agent.
	EnrollmentID *string `json:"enrollment_id,omitempty" codec:"enrollment_id,omitempty" bson:"enrollment_id" yaml:"enrollment_id,omitempty" faker:"-"`
	// ID the primary key for the model instance
	ID string `json:"id" codec:"id" bson:"_id" yaml:"id" faker:"-"`
	// IntegrationInstanceID the integration instance id
	IntegrationInstanceID *string `json:"integration_instance_id,omitempty" codec:"integration_instance_id,omitempty" bson:"integration_instance_id" yaml:"integration_instance_id,omitempty" faker:"-"`
	// RefID the source system id for the model instance
	RefID string `json:"ref_id" codec:"ref_id" bson:"ref_id" yaml:"ref_id" faker:"-"`
	// RefType the source system identifier for the model instance
	RefType string `json:"ref_type" codec:"ref_type" bson:"ref_type" yaml:"ref_type" faker:"-"`
	// SessionID A unique session ID generated by the client which the response will include to capture it more easily
	SessionID string `json:"session_id" codec:"session_id" bson:"session_id" yaml:"session_id" faker:"-"`
	// Hashcode stores the hash of the value of this object whereby two objects with the same hashcode are functionality equal
	Hashcode string `json:"hashcode" codec:"hashcode" bson:"hashcode" yaml:"hashcode" faker:"-"`
}

// ensure that this type implements the data model interface
var _ datamodel.Model = (*ValidateRequest)(nil)

// ensure that this type implements the streamed data model interface
var _ datamodel.StreamedModel = (*ValidateRequest)(nil)

func toValidateRequestObject(o interface{}, isoptional bool) interface{} {
	switch v := o.(type) {
	case *ValidateRequest:
		return v.ToMap()

	default:
		return o
	}
}

// String returns a string representation of ValidateRequest
func (o *ValidateRequest) String() string {
	return fmt.Sprintf("agent.ValidateRequest<%s>", o.ID)
}

// GetTopicName returns the name of the topic if evented
func (o *ValidateRequest) GetTopicName() datamodel.TopicNameType {
	return ""
}

// GetStreamName returns the name of the stream
func (o *ValidateRequest) GetStreamName() string {
	return ""
}

// GetTableName returns the name of the table
func (o *ValidateRequest) GetTableName() string {
	return ""
}

// GetModelName returns the name of the model
func (o *ValidateRequest) GetModelName() datamodel.ModelNameType {
	return ValidateRequestModelName
}

// NewValidateRequestID provides a template for generating an ID field for ValidateRequest
func NewValidateRequestID(customerID string, refType string, refID string) string {
	return hash.Values("ValidateRequest", customerID, refType, refID)
}

func (o *ValidateRequest) setDefaults(frommap bool) {

	if o.ID == "" {
		// we will attempt to generate a consistent, unique ID from a hash
		o.ID = hash.Values("ValidateRequest", o.CustomerID, o.RefType, o.GetRefID())
	}

	if frommap {
		o.FromMap(map[string]interface{}{})
	}
	o.GetRefID()
	o.Hash()
}

// GetID returns the ID for the object
func (o *ValidateRequest) GetID() string {
	return o.ID
}

// GetTopicKey returns the topic message key when sending this model as a ModelSendEvent
func (o *ValidateRequest) GetTopicKey() string {
	return ""
}

// GetTimestamp returns the timestamp for the model or now if not provided
func (o *ValidateRequest) GetTimestamp() time.Time {
	return time.Now().UTC()
}

// GetRefID returns the RefID for the object
func (o *ValidateRequest) GetRefID() string {
	return o.RefID
}

// IsMaterialized returns true if the model is materialized
func (o *ValidateRequest) IsMaterialized() bool {
	return false
}

// IsMutable returns true if the model is mutable
func (o *ValidateRequest) IsMutable() bool {
	return false
}

// GetModelMaterializeConfig returns the materialization config if materialized or nil if not
func (o *ValidateRequest) GetModelMaterializeConfig() *datamodel.ModelMaterializeConfig {
	return nil
}

// IsEvented returns true if the model supports eventing and implements ModelEventProvider
func (o *ValidateRequest) IsEvented() bool {
	return false
}

// SetEventHeaders will set any event headers for the object instance
func (o *ValidateRequest) SetEventHeaders(kv map[string]string) {
	kv["customer_id"] = o.CustomerID
	kv["model"] = ValidateRequestModelName.String()
}

// GetTopicConfig returns the topic config object
func (o *ValidateRequest) GetTopicConfig() *datamodel.ModelTopicConfig {
	return nil
}

// GetCustomerID will return the customer_id
func (o *ValidateRequest) GetCustomerID() string {

	return o.CustomerID

}

// Clone returns an exact copy of ValidateRequest
func (o *ValidateRequest) Clone() datamodel.Model {
	c := new(ValidateRequest)
	c.FromMap(o.ToMap())
	return c
}

// Anon returns the data structure as anonymous data
func (o *ValidateRequest) Anon() datamodel.Model {
	c := new(ValidateRequest)
	if err := faker.FakeData(c); err != nil {
		panic("couldn't create anon version of object: " + err.Error())
	}
	kv := c.ToMap()
	for k, v := range o.ToMap() {
		if _, ok := kv[k]; !ok {
			kv[k] = v
		}
	}
	c.FromMap(kv)
	return c
}

// MarshalJSON returns the bytes for marshaling to json
func (o *ValidateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.ToMap())
}

// UnmarshalJSON will unmarshal the json buffer into the object
func (o *ValidateRequest) UnmarshalJSON(data []byte) error {
	kv := make(map[string]interface{})
	if err := json.Unmarshal(data, &kv); err != nil {
		return err
	}
	o.FromMap(kv)
	if idstr, ok := kv["id"].(string); ok {
		o.ID = idstr
	}
	return nil
}

// Stringify returns the object in JSON format as a string
func (o *ValidateRequest) Stringify() string {
	o.Hash()
	return pjson.Stringify(o)
}

// StringifyPretty returns the object in JSON format as a string prettified
func (o *ValidateRequest) StringifyPretty() string {
	o.Hash()
	return pjson.Stringify(o, true)
}

// IsEqual returns true if the two ValidateRequest objects are equal
func (o *ValidateRequest) IsEqual(other *ValidateRequest) bool {
	return o.Hash() == other.Hash()
}

// ToMap returns the object as a map
func (o *ValidateRequest) ToMap() map[string]interface{} {
	o.setDefaults(false)
	return map[string]interface{}{
		"config":                  toValidateRequestObject(o.Config, false),
		"customer_id":             toValidateRequestObject(o.CustomerID, false),
		"enrollment_id":           toValidateRequestObject(o.EnrollmentID, true),
		"id":                      toValidateRequestObject(o.ID, false),
		"integration_instance_id": toValidateRequestObject(o.IntegrationInstanceID, true),
		"ref_id":                  toValidateRequestObject(o.RefID, false),
		"ref_type":                toValidateRequestObject(o.RefType, false),
		"session_id":              toValidateRequestObject(o.SessionID, false),
		"hashcode":                toValidateRequestObject(o.Hashcode, false),
	}
}

// FromMap attempts to load data into object from a map
func (o *ValidateRequest) FromMap(kv map[string]interface{}) {

	o.ID = ""

	// if coming from db
	if id, ok := kv["_id"]; ok && id != "" {
		kv["id"] = id
	}
	if val, ok := kv["config"].(string); ok {
		o.Config = val
	} else {
		if val, ok := kv["config"]; ok {
			if val == nil {
				o.Config = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.Config = fmt.Sprintf("%v", val)
			}
		}
	}
	if val, ok := kv["customer_id"].(string); ok {
		o.CustomerID = val
	} else {
		if val, ok := kv["customer_id"]; ok {
			if val == nil {
				o.CustomerID = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.CustomerID = fmt.Sprintf("%v", val)
			}
		}
	}
	if val, ok := kv["enrollment_id"].(*string); ok {
		o.EnrollmentID = val
	} else if val, ok := kv["enrollment_id"].(string); ok {
		o.EnrollmentID = &val
	} else {
		if val, ok := kv["enrollment_id"]; ok {
			if val == nil {
				o.EnrollmentID = pstrings.Pointer("")
			} else {
				// if coming in as map, convert it back
				if kv, ok := val.(map[string]interface{}); ok {
					val = kv["string"]
				}
				o.EnrollmentID = pstrings.Pointer(fmt.Sprintf("%v", val))
			}
		}
	}
	if val, ok := kv["id"].(string); ok {
		o.ID = val
	} else {
		if val, ok := kv["id"]; ok {
			if val == nil {
				o.ID = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.ID = fmt.Sprintf("%v", val)
			}
		}
	}
	if val, ok := kv["integration_instance_id"].(*string); ok {
		o.IntegrationInstanceID = val
	} else if val, ok := kv["integration_instance_id"].(string); ok {
		o.IntegrationInstanceID = &val
	} else {
		if val, ok := kv["integration_instance_id"]; ok {
			if val == nil {
				o.IntegrationInstanceID = pstrings.Pointer("")
			} else {
				// if coming in as map, convert it back
				if kv, ok := val.(map[string]interface{}); ok {
					val = kv["string"]
				}
				o.IntegrationInstanceID = pstrings.Pointer(fmt.Sprintf("%v", val))
			}
		}
	}
	if val, ok := kv["ref_id"].(string); ok {
		o.RefID = val
	} else {
		if val, ok := kv["ref_id"]; ok {
			if val == nil {
				o.RefID = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.RefID = fmt.Sprintf("%v", val)
			}
		}
	}
	if val, ok := kv["ref_type"].(string); ok {
		o.RefType = val
	} else {
		if val, ok := kv["ref_type"]; ok {
			if val == nil {
				o.RefType = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.RefType = fmt.Sprintf("%v", val)
			}
		}
	}
	if val, ok := kv["session_id"].(string); ok {
		o.SessionID = val
	} else {
		if val, ok := kv["session_id"]; ok {
			if val == nil {
				o.SessionID = ""
			} else {
				v := pstrings.Value(val)
				if v != "" {
					if m, ok := val.(map[string]interface{}); ok && m != nil {
						val = pjson.Stringify(m)
					}
				} else {
					val = v
				}
				o.SessionID = fmt.Sprintf("%v", val)
			}
		}
	}
	o.setDefaults(false)
}

// Hash will return a hashcode for the object
func (o *ValidateRequest) Hash() string {
	args := make([]interface{}, 0)
	args = append(args, o.Config)
	args = append(args, o.CustomerID)
	args = append(args, o.EnrollmentID)
	args = append(args, o.ID)
	args = append(args, o.IntegrationInstanceID)
	args = append(args, o.RefID)
	args = append(args, o.RefType)
	args = append(args, o.SessionID)
	o.Hashcode = hash.Values(args...)
	return o.Hashcode
}

// SetIntegrationInstanceID will set the integration instance ID
func (o *ValidateRequest) SetIntegrationInstanceID(id string) {
	if id == "" {
		o.IntegrationInstanceID = nil
	} else {
		o.IntegrationInstanceID = &id
	}
}

// GetIntegrationInstanceID will return the integration instance ID
func (o *ValidateRequest) GetIntegrationInstanceID() *string {
	return o.IntegrationInstanceID
}

// ValidateRequestPartial is a partial struct for upsert mutations for ValidateRequest
type ValidateRequestPartial struct {
	// Config The configuration from the UI to be validated in JSON format as a string
	Config *string `json:"config,omitempty"`
	// EnrollmentID The id of the on premise agent enrollment to route this to. Leave null for cloud agent.
	EnrollmentID *string `json:"enrollment_id,omitempty"`
	// SessionID A unique session ID generated by the client which the response will include to capture it more easily
	SessionID *string `json:"session_id,omitempty"`
}

var _ datamodel.PartialModel = (*ValidateRequestPartial)(nil)

// GetModelName returns the name of the model
func (o *ValidateRequestPartial) GetModelName() datamodel.ModelNameType {
	return ValidateRequestModelName
}

// ToMap returns the object as a map
func (o *ValidateRequestPartial) ToMap() map[string]interface{} {
	kv := map[string]interface{}{
		"config":        toValidateRequestObject(o.Config, true),
		"enrollment_id": toValidateRequestObject(o.EnrollmentID, true),
		"session_id":    toValidateRequestObject(o.SessionID, true),
	}
	for k, v := range kv {
		if v == nil || reflect.ValueOf(v).IsZero() {
			delete(kv, k)
		} else {
		}
	}
	return kv
}

// Stringify returns the object in JSON format as a string
func (o *ValidateRequestPartial) Stringify() string {
	return pjson.Stringify(o.ToMap())
}

// MarshalJSON returns the bytes for marshaling to json
func (o *ValidateRequestPartial) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.ToMap())
}

// UnmarshalJSON will unmarshal the json buffer into the object
func (o *ValidateRequestPartial) UnmarshalJSON(data []byte) error {
	kv := make(map[string]interface{})
	if err := json.Unmarshal(data, &kv); err != nil {
		return err
	}
	o.FromMap(kv)
	return nil
}

func (o *ValidateRequestPartial) setDefaults(frommap bool) {
}

// FromMap attempts to load data into object from a map
func (o *ValidateRequestPartial) FromMap(kv map[string]interface{}) {
	if val, ok := kv["config"].(*string); ok {
		o.Config = val
	} else if val, ok := kv["config"].(string); ok {
		o.Config = &val
	} else {
		if val, ok := kv["config"]; ok {
			if val == nil {
				o.Config = pstrings.Pointer("")
			} else {
				// if coming in as map, convert it back
				if kv, ok := val.(map[string]interface{}); ok {
					val = kv["string"]
				}
				o.Config = pstrings.Pointer(fmt.Sprintf("%v", val))
			}
		}
	}
	if val, ok := kv["enrollment_id"].(*string); ok {
		o.EnrollmentID = val
	} else if val, ok := kv["enrollment_id"].(string); ok {
		o.EnrollmentID = &val
	} else {
		if val, ok := kv["enrollment_id"]; ok {
			if val == nil {
				o.EnrollmentID = pstrings.Pointer("")
			} else {
				// if coming in as map, convert it back
				if kv, ok := val.(map[string]interface{}); ok {
					val = kv["string"]
				}
				o.EnrollmentID = pstrings.Pointer(fmt.Sprintf("%v", val))
			}
		}
	}
	if val, ok := kv["session_id"].(*string); ok {
		o.SessionID = val
	} else if val, ok := kv["session_id"].(string); ok {
		o.SessionID = &val
	} else {
		if val, ok := kv["session_id"]; ok {
			if val == nil {
				o.SessionID = pstrings.Pointer("")
			} else {
				// if coming in as map, convert it back
				if kv, ok := val.(map[string]interface{}); ok {
					val = kv["string"]
				}
				o.SessionID = pstrings.Pointer(fmt.Sprintf("%v", val))
			}
		}
	}
	o.setDefaults(false)
}
